<a href="https://colab.research.google.com/github/shims94/230620_numpy_02/blob/main/230620_numpy_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pip install numpy
import numpy as np

In [ ]:
#@title 1차원 배열
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.array(range(3))

array([0, 1, 2])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
#@title 벡터화 연산
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
a % 7

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [ ]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
(a > 5) & (a < 7)

array([False, False, False, False, False, False,  True, False, False,
       False])

In [ ]:
#@title 2차원 배열
arr = np.array([[0, 1, 2], [3, 4, 5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.arange(6).reshape(2, -1)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr, arr.ndim, arr.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [ ]:
#@title 3차원배열
t = np.arange(24).reshape(2, 3, -1)
t, t.ndim, t.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 3,
 (2, 3, 4))

In [ ]:
#@title 배열 복사
v = t.view()
c = t.copy()
t[0][0] = 100
t, v,

(array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]))

In [ ]:
#@title 배열의 인덱싱
# 일차원 배열 = 리스트의 인덱싱
a = np.arange(5)
print(a)
a[0], a[-1]

[0 1 2 3 4]


(0, 4)

In [ ]:
# 다차원 배열 -> [] -> ,를 통해서 축을 구분
b = np.arange(6).reshape(2, -1)
b, b.ndim, b.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [ ]:
b[0, 0]

0

In [ ]:
b[0, 0] = 200
b

array([[200,   1,   2],
       [  3,   4,   5]])

In [ ]:
#@title 배열 슬라이싱
# 다차원 배열 슬라이싱 -> 파이썬 슬라이싱 + 축(axis) ,를 같이 쓰면 된다
a = np.arange(8).reshape(2, -1)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[0], a[0, :]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
a[:, 1]

array([1, 5])

In [ ]:
a[1, 1:]

array([5, 6, 7])

In [ ]:
a[1:3, 0:2]

array([[4, 5]])

In [ ]:
#@title 배열 인덱싱 (불리언 배열, 정수 배열)
# 불리언 배열
a1 = np.arange(1, 10, 2)
a2 = np.arange(1, 10)
a1, a2[a2 % 2 != 0], a2[::2]

(array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [ ]:
# 정수 배열
a2[np.arange(0, 9, 3)]

array([1, 4, 7])